# Generated by Django 5.1.4 on 2024-12-25 01:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('인건비', '인건비'), ('연구수당', '연구수당'), ('연구시설/장비비', '연구시설/장비비'), ('연구활동비', '연구활동비'), ('연구재료비', '연구재료비'), ('간접비', '간접비'), ('통장이자', '통장이자'), ('위탁연구개발비', '위탁연구개발비'), ('보안수당', '보안수당'), ('연구윤리활동비', '연구윤리활동비'), ('연구실안전관리비', '연구실안전관리비')], max_length=50, verbose_name='예산항목')),
            ],
            options={
                'verbose_name': '예산항목',
                'verbose_name_plural': '예산항목 목록',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학과명')),
                ('code', models.CharField(max_length=20, verbose_name='학과코드')),
            ],
            options={
                'verbose_name': '학과',
                'verbose_name_plural': '학과 목록',
            },
        ),
        migrations.CreateModel(
            name='BudgetSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='연구비항목')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='research.budgetcategory', verbose_name='예산항목')),
            ],
            options={
                'verbose_name': '연구비항목',
                'verbose_name_plural': '연구비항목 목록',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('military_id', models.CharField(max_length=10, unique=True, verbose_name='군번')),
                ('rank', models.CharField(blank=True, choices=[('교수', '교수'), ('부교수', '부교수'), ('조교수', '조교수'), ('강사', '강사'), ('이등병', '이등병'), ('일병', '일병'), ('상병', '상병'), ('병장', '병장'), ('하사', '하사'), ('중사', '중사'), ('상사', '상사'), ('원사', '원사'), ('준위', '준위'), ('소위', '소위'), ('중위', '중위'), ('대위', '대위'), ('소령', '소령'), ('중령', '중령'), ('대령', '대령'), ('대령(진)', '대령(진)'), ('대령(임)', '대령(임)'), ('중령(진)', '중령(진)'), ('중령(임)', '중령(임)'), ('소령(진)', '소령(진)'), ('소령(임)', '소령(임)'), ('대위(진)', '대위(진)'), ('대위(임)', '대위(임)'), ('중위(진)', '중위(진)'), ('중위(임)', '중위(임)'), ('소위(진)', '소위(진)'), ('소위(임)', '소위(임)'), ('원사(진)', '원사(진)'), ('원사(임)', '원사(임)'), ('상사(진)', '상사(진)'), ('상사(임)', '상사(임)'), ('중사(진)', '중사(진)'), ('중사(임)', '중사(임)'), ('하사(진)', '하사(진)'), ('하사(임)', '하사(임)')], max_length=20, null=True, verbose_name='계급')),
                ('internal_external', models.CharField(choices=[('internal', '내부'), ('external', '외부')], max_length=10, verbose_name='내/외부구분')),
                ('status', models.CharField(choices=[('군무원', '군무원'), ('생도', '생도'), ('민간인', '민간인'), ('현역', '현역'), ('연구원', '연구원'), ('예비역', '예비역'), ('조교수', '조교수'), ('학생연구원', '학생연구원')], max_length=20, verbose_name='신분구분')),
                ('position', models.CharField(blank=True, choices=[('교수', '교수'), ('부교수', '부교수'), ('조교수(전임)', '조교수(전임)'), ('조교수(일반)', '조교수(일반)'), ('군교관', '군교관'), ('강사', '강사'), ('외래강사', '외래강사')], max_length=20, null=True, verbose_name='직위')),
                ('approval_authority', models.CharField(blank=True, choices=[('산학협력팀장', '산학협력팀장'), ('과제운영팀장', '과제운영팀장')], max_length=20, null=True, verbose_name='결재권한')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.department', verbose_name='소속')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=20, unique=True, verbose_name='과제번호')),
                ('project_name', models.CharField(max_length=200, verbose_name='과제명')),
                ('ordering_organization', models.CharField(max_length=100, verbose_name='발주기관')),
                ('contract_from', models.DateField(verbose_name='계약시작일')),
                ('contract_to', models.DateField(verbose_name='계약종료일')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='연구비 총액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to=settings.AUTH_USER_MODEL, verbose_name='연구책임자')),
                ('researchers', models.ManyToManyField(blank=True, related_name='participating_projects', to=settings.AUTH_USER_MODEL, verbose_name='연구원')),
            ],
            options={
                'verbose_name': '연구과제',
                'verbose_name_plural': '연구과제 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, verbose_name='신청번호')),
                ('application_date', models.DateField(verbose_name='신청일자')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='집행일자')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='신청금액')),
                ('description', models.TextField(verbose_name='신청내용')),
                ('status', models.CharField(choices=[('신청', '신청'), ('검토', '검토'), ('결재', '결재')], default='신청', max_length=10, verbose_name='상태')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='기각사유')),
                ('budget_subcategory', models.CharField(max_length=100, verbose_name='연구비항목')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '연구비신청',
                'verbose_name_plural': '연구비신청 목록',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='파일명')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchapplication', verbose_name='신청서')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일 목록',
            },
        ),
        migrations.CreateModel(
            name='ResearchBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('인건비', '인건비'), ('연구수당', '연구수당'), ('연구시설/장비비', '연구시설/장비비'), ('연구활동비', '연구활동비'), ('연구재료비', '연구재료비'), ('간접비', '간접비'), ('통장이자', '통장이자'), ('위탁연구개발비', '위탁연구개발비'), ('보안수당', '보안수당'), ('연구윤리활동비', '연구윤리활동비'), ('연구실안전관리비', '연구실안전관리비')], max_length=50, verbose_name='예산항목')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='예산액')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='잔액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='research.research', verbose_name='연구과제')),
            ],
            options={
                'verbose_name': '연구예산',
                'verbose_name_plural': '연구예산 목록',
                'unique_together': {('research', 'budget_type')},
            },
        ),
        migrations.AddField(
            model_name='researchapplication',
            name='research_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchbudget', verbose_name='연구과제'),
        ),
        migrations.CreateModel(
            name='ResearchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='카드번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용가능여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='research.research')),
            ],
            options={
                'verbose_name': '연구비카드',
                'verbose_name_plural': '연구비카드 목록',
                'unique_together': {('research', 'card_number')},
            },
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_username', models.CharField(max_length=150, verbose_name='사용할 ID')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('reason', models.TextField(verbose_name='신청 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인'), ('rejected', '거절')], default='pending', max_length=10, verbose_name='상태')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일시')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='거절 사유')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '관리자 신청',
                'verbose_name_plural': '관리자 신청 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('국민', '국민'), ('기업', '기업'), ('NH농협', 'NH농협'), ('신한', '신한'), ('우체국', '우체국'), ('SC', 'SC'), ('하나', '하나'), ('한국씨티', '한국씨티'), ('우리', '우리'), ('산업', '산업'), ('새마을금고연합회', '새마을금고연합회'), ('케이뱅크', '케이뱅크'), ('카카오', '카카오'), ('토스', '토스')], max_length=20, verbose_name='은행')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(max_length=100, verbose_name='예금주')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본계좌여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 계좌정보',
                'verbose_name_plural': '사용자 계좌정보 목록',
                'unique_together': {('user', 'bank_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_card', models.BooleanField(default=False, verbose_name='카드사용여부')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research.researchapplication', verbose_name='신청서')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.researchcard', verbose_name='연구비카드')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.userbankaccount', verbose_name='계좌정보')),
            ],
            options={
                'verbose_name': '지불방법',
                'verbose_name_plural': '지불방법 목록',
            },
        ),
    ]
